services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5555:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
