/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BoardsImport } from './routes/boards'
import { Route as BoardImport } from './routes/board'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardUsersImport } from './routes/dashboard/users'
import { Route as DashboardTeamsImport } from './routes/dashboard/teams'
import { Route as DashboardSupportImport } from './routes/dashboard/support'
import { Route as DashboardAccountingImport } from './routes/dashboard/accounting'
import { Route as BoardBoardIdImport } from './routes/board/$boardId'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLogoutImport } from './routes/auth/logout'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as BoardBoardIdCardCardIdImport } from './routes/board/$boardId/card/$cardId'

// Create/Update Routes

const BoardsRoute = BoardsImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRoute,
} as any)

const BoardRoute = BoardImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersRoute = DashboardUsersImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRoute,
} as any)

const DashboardTeamsRoute = DashboardTeamsImport.update({
  id: '/dashboard/teams',
  path: '/dashboard/teams',
  getParentRoute: () => rootRoute,
} as any)

const DashboardSupportRoute = DashboardSupportImport.update({
  id: '/dashboard/support',
  path: '/dashboard/support',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAccountingRoute = DashboardAccountingImport.update({
  id: '/dashboard/accounting',
  path: '/dashboard/accounting',
  getParentRoute: () => rootRoute,
} as any)

const BoardBoardIdRoute = BoardBoardIdImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => BoardRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLogoutRoute = AuthLogoutImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const BoardBoardIdCardCardIdRoute = BoardBoardIdCardCardIdImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => BoardBoardIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardImport
      parentRoute: typeof rootRoute
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdImport
      parentRoute: typeof BoardImport
    }
    '/dashboard/accounting': {
      id: '/dashboard/accounting'
      path: '/dashboard/accounting'
      fullPath: '/dashboard/accounting'
      preLoaderRoute: typeof DashboardAccountingImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/dashboard/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/board/$boardId/card/$cardId': {
      id: '/board/$boardId/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/board/$boardId/card/$cardId'
      preLoaderRoute: typeof BoardBoardIdCardCardIdImport
      parentRoute: typeof BoardBoardIdImport
    }
  }
}

// Create and export the route tree

interface BoardBoardIdRouteChildren {
  BoardBoardIdCardCardIdRoute: typeof BoardBoardIdCardCardIdRoute
}

const BoardBoardIdRouteChildren: BoardBoardIdRouteChildren = {
  BoardBoardIdCardCardIdRoute: BoardBoardIdCardCardIdRoute,
}

const BoardBoardIdRouteWithChildren = BoardBoardIdRoute._addFileChildren(
  BoardBoardIdRouteChildren,
)

interface BoardRouteChildren {
  BoardBoardIdRoute: typeof BoardBoardIdRouteWithChildren
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardBoardIdRoute: BoardBoardIdRouteWithChildren,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRouteWithChildren
  '/boards': typeof BoardsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$boardId': typeof BoardBoardIdRouteWithChildren
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/board/$boardId/card/$cardId': typeof BoardBoardIdCardCardIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRouteWithChildren
  '/boards': typeof BoardsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$boardId': typeof BoardBoardIdRouteWithChildren
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/board/$boardId/card/$cardId': typeof BoardBoardIdCardCardIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRouteWithChildren
  '/boards': typeof BoardsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$boardId': typeof BoardBoardIdRouteWithChildren
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/board/$boardId/card/$cardId': typeof BoardBoardIdCardCardIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/board'
    | '/boards'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/board/$boardId'
    | '/dashboard/accounting'
    | '/dashboard/support'
    | '/dashboard/teams'
    | '/dashboard/users'
    | '/dashboard'
    | '/board/$boardId/card/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board'
    | '/boards'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/board/$boardId'
    | '/dashboard/accounting'
    | '/dashboard/support'
    | '/dashboard/teams'
    | '/dashboard/users'
    | '/dashboard'
    | '/board/$boardId/card/$cardId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/board'
    | '/boards'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/board/$boardId'
    | '/dashboard/accounting'
    | '/dashboard/support'
    | '/dashboard/teams'
    | '/dashboard/users'
    | '/dashboard/'
    | '/board/$boardId/card/$cardId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardRoute: typeof BoardRouteWithChildren
  BoardsRoute: typeof BoardsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DashboardAccountingRoute: typeof DashboardAccountingRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardRoute: BoardRouteWithChildren,
  BoardsRoute: BoardsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSignupRoute: AuthSignupRoute,
  DashboardAccountingRoute: DashboardAccountingRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/board",
        "/boards",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/logout",
        "/auth/signup",
        "/dashboard/accounting",
        "/dashboard/support",
        "/dashboard/teams",
        "/dashboard/users",
        "/dashboard/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/board": {
      "filePath": "board.tsx",
      "children": [
        "/board/$boardId"
      ]
    },
    "/boards": {
      "filePath": "boards.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/logout": {
      "filePath": "auth/logout.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/board/$boardId": {
      "filePath": "board/$boardId.tsx",
      "parent": "/board",
      "children": [
        "/board/$boardId/card/$cardId"
      ]
    },
    "/dashboard/accounting": {
      "filePath": "dashboard/accounting.tsx"
    },
    "/dashboard/support": {
      "filePath": "dashboard/support.tsx"
    },
    "/dashboard/teams": {
      "filePath": "dashboard/teams.tsx"
    },
    "/dashboard/users": {
      "filePath": "dashboard/users.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/board/$boardId/card/$cardId": {
      "filePath": "board/$boardId/card/$cardId.tsx",
      "parent": "/board/$boardId"
    }
  }
}
ROUTE_MANIFEST_END */
